[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68" 
bytes = "1.3.0"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive"] }  # core Serde + derive macros
serde_json = "1.0"  